### ISSUE TITLE
Mobile app data is not capturing in har file

### ISSUE THREAD

**Issue by sanjayahuja** [ericbeland/browsermob-proxy-rb#30]
Hi, I am trying to capture mobile app network traffic in appium. I am able to start browser mob server and save har file but it only contains default header no traffic related to mobile app. here's my code. Kindly help

server = BrowserMob::Proxy::Server.new('~/Downloads/browsermob-proxy/bin/browsermob-proxy')
server.start
proxy = server.create_proxy #=> #<BrowserMob::Proxy::Client:0x0000010224bdc0 ...>
proxy.new_har "my_har"
capabilities = capabilities.merge(deviceName: ENV['DEVICE'], proxy: proxy.selenium_proxy)
har = proxy.har
har.save_to "~/Downloads/my_har.har"

**Comment by ericbeland** [comment]
Hi, we are closing older tickets out. I hope this problem was resolved for you.
