### ISSUE TITLE
BMP(2.52.4) only captures POST requests to OCSP for firefox(47.0.1)

### ISSUE THREAD

**Issue by yicheny001** [ericbeland/browsermob-proxy-rb#33]
I only see post requests to OCSP and nothing else. I've configured true for all three criteria (capture content, capture headers, capture binary data) when setting up the driver:

```
require 'selenium/webdriver' 
require 'browsermob/proxy'
server = BrowserMob::Proxy::Server.new("/Users/pairing/Downloads/browsermob-proxy-2.1.2/bin/browsermob-proxy") 

proxy = server.create_proxy

profile = Selenium::WebDriver::Firefox::Profile.new 
profile.proxy = proxy.selenium_proxy

driver = Selenium::WebDriver.for(:firefox, :profile => profile)
opts = {:capture_binary_content=> true, :capture_content => true, :capture_headers => true}
proxy.new_har("netflix", opts)

driver.get "https://www.netflix.com"

har = proxy.har 
sleep(10) #=> how long do you want the website to load
jsonHar = har.to_json
```

any advice on why it's not capturing the actual site content?

**Comment by srlesrle** [comment]
same here :(
http://stackoverflow.com/questions/40730738/watir-webdriver-browsermob-proxy-har-file-almost-empty

**Comment by srlesrle** [comment]
ok here some tests results:
firefox 49 2.0.0 don't work at all
firefox 49 2.1.2 don't work at all
firefox 48 2.1.2 don't work at all

firefox 47 2.1.2 works but har is small
firefox 47 2.0.0 works har file is bigger
firefox 47 2.1.0 works har is middle big
firefox 47 2.1.1 works and it is biggest

Then I tested also with firefox 46 and got same results....

I remember a couple years ago I got also the redirects with same codes and now can get it :(

here are codes one more time

`server = BrowserMob::Proxy::Server.new("/home/da/Downloads/browsermob-proxy-2.1.2/bin/browsermob-proxy") #=> #<BrowserMob::Proxy::Server:0x000001022c6ea8 ...>
			server.start
      @@proxy = server.create_proxy(9090)
			puts @@proxy.inspect
      profile = Selenium::WebDriver::Firefox::Profile.new
			puts "going on #{dv}"
      profile['general.useragent.override'] = dv['useragent']
			#'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:27.0) Gecko/20100101 Firefox/27.0'#device['useragent']
      puts dv['useragent']
      profile.proxy = Selenium::WebDriver::Proxy.new :http => 'localhost:9090', :ssl => 'localhost:9090'#9091
      time = Time.now.to_i #Time.now.getutc
      puts APP_ROOT
			opts = {:capture_binary_content=> true, :capture_content => true, :capture_headers => true}

      @@proxy.new_har time, opts
      @@b = Watir::Browser.new :firefox, :profile => profile

			@@har = @@proxy.har #=> #<HAR::Archive:0x-27066c42d7e75fa6>
			#har.entries.first.request.url
			#har.entries.first.request.url #=> "http://google.com"
			@@b.goto "http://domain that redirects.com/click.php?"
			puts @@har.inspect
			@@har.save_to "#{APP_ROOT}/har/google.har"
			exit`

here is biggest har file:

`{"log":{"version":"1.2","creator":{"name":"BrowserMob Proxy","version":"2.1.1","comment":""},"browser":{"name":"IE","version":"11.0","comment":""},"pages":[{"id":"1479851900","startedDateTime":"2016-11-22T22:58:22.290+01:00","title":"1479851900","pageTimings":{"comment":""},"comment":""}],"entries":[{"pageref":"1479851900","startedDateTime":"2016-11-22T22:58:29.150+01:00","request":{"method":"GET","url":"https://tiles.services.mozilla.com/v3/links/fetch/en-US/release","httpVersion":"HTTP/1.1","cookies":[],"headers":[{"name":"Host","value":"tiles.services.mozilla.com"},{"name":"User-Agent","value":"Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"},{"name":"Accept","value":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},{"name":"Accept-Language","value":"en-US,en;q=0.5"},{"name":"Accept-Encoding","value":"gzip, deflate, br"},{"name":"Content-Type","value":"application/json"},{"name":"Connection","value":"keep-alive"}],"queryString":[],"headersSize":362,"bodySize":0,"comment":""},"response":{"status":303,"statusText":"SEE OTHER","httpVersion":"HTTP/1.1","cookies":[],"headers":[{"name":"Content-Type","value":"text/html; charset=utf-8"},{"name":"Date","value":"Tue, 22 Nov 2016 21:58:29 GMT"},{"name":"Location","value":"https://tiles-cloudfront.cdn.mozilla.net/desktop/STAR/en-US.edf14b5c63daee79d6fd989a48b71b0adfb989b4.ag.json"},{"name":"Content-Length","value":"0"},{"name":"Connection","value":"keep-alive"}],"content":{"size":0,"mimeType":"text/html; charset=utf-8","text":"","comment":""},"redirectURL":"https://tiles-cloudfront.cdn.mozilla.net/desktop/STAR/en-US.edf14b5c63daee79d6fd989a48b71b0adfb989b4.ag.json","headersSize":268,"bodySize":0,"comment":""},"cache":{},"timings":{"comment":"","dns":61,"connect":3995,"send":47,"wait":173,"receive":45,"blocked":0,"ssl":3739},"serverIPAddress":"52.34.245.108","comment":"","time":4323},{"pageref":"1479851900","startedDateTime":"2016-11-22T22:58:29.315+01:00","request":{"method":"POST","url":"https://location.services.mozilla.com/v1/country?key=7e40f68c-7938-4c5d-9f95-e61647c213eb","httpVersion":"HTTP/1.1","cookies":[],"headers":[{"name":"Host","value":"location.services.mozilla.com"},{"name":"User-Agent","value":"Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"},{"name":"Accept","value":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},{"name":"Accept-Language","value":"en-US,en;q=0.5"},{"name":"Accept-Encoding","value":"gzip, deflate, br"},{"name":"Content-Type","value":"application/json"},{"name":"Content-Length","value":"2"},{"name":"Connection","value":"keep-alive"}],"queryString":[{"name":"key","value":"7e40f68c-7938-4c5d-9f95-e61647c213eb"}],"postData":{"mimeType":"application/json","text":"{}","comment":""},"headersSize":408,"bodySize":2,"comment":""},"response":{"status":200,"statusText":"OK","httpVersion":"HTTP/1.1","cookies":[],"headers":[{"name":"Access-Control-Allow-Origin","value":"*"},{"name":"Access-Control-Max-Age","value":"2592000"},{"name":"Content-Type","value":"application/json; charset=UTF-8"},{"name":"Date","value":"Tue, 22 Nov 2016 21:58:29 GMT"},{"name":"Server","value":"nginx"},{"name":"Content-Length","value":"49"},{"name":"Connection","value":"keep-alive"}],"content":{"size":49,"mimeType":"application/json; charset=UTF-8","text":"{\"country_name\": \"Germany\", \"country_code\": \"DE\"}","comment":""},"redirectURL":"","headersSize":229,"bodySize":49,"comment":""},"cache":{},"timings":{"comment":"","dns":18,"connect":2509,"send":214,"wait":45,"receive":21,"blocked":0,"ssl":2435},"serverIPAddress":"54.229.192.165","comment":"","time":2809}],"comment":""}}`

it seems that it takes only some firefox things, but nothing else :(

**Comment by ericbeland** [comment]
Closing per @rriemann
